import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/WeatherFooter";
import Navbar from "@/components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "WeatherHub",
  description: "Generated by create next app",
  icons: {
    icon: "/weathericon.png", // replace with your icon file name in /public
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body

      
        
      >
        <Navbar/>
        {children}

       
      </body>
    </html>
  );
}
